 <%@page import="EntityDatabase.AdminRegister"%>
 <%@page import="com.Singletone.SessionFactoryInfo"%>
 <%@page import="com.DaoClass.ViewJob"%>
 <%@page import="EntityDatabase.JobPost"%>
 <%@page import="java.util.*"%>
 <%@page import="org.hibernate.Transaction" %>
 <%@page import="org.hibernate.Session" %>
 <%@page import="org.hibernate.query.Query" %>
 <%@page import="org.hibernate.query.NativeQuery" %>